---
# tasks file for tendrl-storage-node-collectd

- name: Restore the settings of groups['gluster-servers'] collectd service
  debug:
    msg:
      - "Restore collectd uploading port from 2023/tcp to 2003/tcp for sending to the carbon-cache."

- name: Restore collectd.d configation file for changing uploading port
  lineinfile:
    path: "{{ item }}"
    regexp: '^.*graphite_port.*'
    line: '        graphite_port "2003"'
  with_items:
    - /etc/collectd.d/tendrl_gluster_brick_disk_stats.conf
    - /etc/collectd.d/tendrl_gluster.conf
 
- name: Restart collectd service
  service:
    name: collectd
    state: restarted
